name: face_studio_mobile_client
description: Minimal mobile client for Face Studio backend API.
publish_to: "none"
version: 0.1.0+28

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.3
  geolocator: ^13.0.1
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.jpeg
    - assets/face_reference.png
    - assets/face_reference.jpeg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.jpeg"
